dist: trusty
language: node_js
node_js:
- lts/*
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
install:
- npm ci
stages:
- name: Test
- name: Publish
  if: branch == master && repo == 'mooyoul/is-webp-extended'
jobs:
  include:
  - stage: Test
    name: Lint
    script: npm run lint
  - stage: Test
    name: Test
    script: npm test
  - stage: Publish
    node_js: lts/carbon
    script: npx semantic-release
    env:
      - secure: wewLIGmBRuwWEogN0aB68gNCizL0n04+n/4RzgVZ//EM6CziGqhU5CPs+WEaNmpjdJttbFwI5kOW6m9EoJZTZA3ywQAkCb0EprbhVY/hpN4cZpvqAExZRxjW/tN1UW0H2/hqjSmshw26VVs7AuAj/21HYcC/GfDyv9n2wfEwAOErphBpkKUOll6vX+e4IO32yJLgwfJ1XlW41vzmiU5t8/SXfDsOJlNNWu1kpeVOJvx7lcqAkE1hhdhzfzD5VbVxkTk2DdvRje6xNlyuNWn5boHFhiE/tz4mYPWG1ZG3B4PUkBbSY8JwZxekZ/3IBK8kL23QZxBduKg6zBLEgZHImz1Fjs9J3hMlloXtgdg87DxIEUB6Dq5LtxVZRTRWIh2hg8qZ6GCpBIrVLrA5le8refwNUfMx67HTlV8LCEFpgRaYcaC42Tuq0w95/FnzXHCzggfYhBztAVdBAIxezYxUSPXDuaR3OCd44YqqEX8ZkvI0OdAAVM61xzdpEpL3b5bqGUhiKgT2PEdZVIErS726qkB2cRQPWgOChZmHvym/oe7AG3oryDYwEuSf51RC+cr6bgwFZ2BtA1iGa9ddhyHCEaBLAvuE6x4yaz52UQy2BuDM/qa8n7u5veydLSeG1V9k8iBGQXcxLJCKwSw90mreUyubvkC5s+11QKIpvi+xSI4=
      - secure: jpUwH1yf4PCC511gD9WmT3gwR12l0jShXaSaWZlL8B05T/yiod3W461STAMyuPysBW6ENcCM7qTLbgkYoKrlyfyMsFWG+c1yZjHpx8LvTFKGVcp5cuuxdRPGeUYSvWQJXNRS8TI4mhOEVDtmu0yizz5ddm0wiBGrJDgZVAnKUA818mSqTwDrFMZBz77Rgid7eG2UNAUpT567LILxi0zQSfXgcnjnsA30pk1+8duabsp/WUQaMc5r75kcRQjtytgxQHNvMIWqOpwbpFU3TBb8YW7qndPl70m8xtD5J79gHU2tuWc3kUq3jEFKGh2wmzbYxY71LikJmimY9bhz7yNCz0Ffoz3b1DHIRvsZiUiw1QI+gH8nCz9GkNnsMmIxwm8wuxu98U07m+OnwFaLglgwZUIdUNgYINu2SDQYFfbg2tfPJBcAK7+H8JfQU+cLp39saPHr4Ygep1Ajvbd6uAK45J7d8LjJC3Vqff2Pq/EKCGJI5cojADnj72dZObxD2vjPWTziUMNHluT094juzQ+YvF77Qi9jU9WxrbvQIGui/0FnCa1ESNKVqm7Xf7q1KmUc/KTi5llMtRXnH/0RqWpuX2n/zZl31HbREOy71UO51EQJsuSneOxMlO6ETDUvFxTjS8IUv9rw3qBHZs3bBdlPz0UgtnC6yeitgQy794SAlRc=

